server:
  port: 8066
  servlet:
    context-path: /api

spring:
  application:
    name: FileCloud # 应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/crfu_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: crfu
    password: crfu123
    driverClassName: com.mysql.cj.jdbc.Driver
  session:
    # 生效时间为一天
    timeout: 86400

  servlet:
    multipart:
      # 设置单次请求的文件的总大小
      max-request-size: 10MB
      # 设置单个文件的大小,
      max-file-size: 10MB

  # 解决swagger和springBoot高版本冲突问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  #mapper路径
  mapper-locations: classpath:mapper/*.xml
  #mapper配置路径
  #  config-location: classpath:static/mybatis/mybatis-config.xml
  global-config:
    # 关闭MP3.0+自带的banner
    banner: false
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: false
    #打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 上传文件配置
file:
  # 允许文件后缀
  suffers:
    - .jpg
    - .png
    - .gif
    - .bmp
    - .jpeg
    - .svg
    - .zip
    - .pdf
  # 黑名单
  blocked:
    - "127.0.0.1"
    - "https://blocked-origin1.com"